//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pocket_Website.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pocket_Website.Language.lang_en", typeof(lang_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string aboutus {
            get {
                return ResourceManager.GetString("aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget: .
        /// </summary>
        public static string budget {
            get {
                return ResourceManager.GetString("budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost:.
        /// </summary>
        public static string costexpenses {
            get {
                return ResourceManager.GetString("costexpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket is blla blla bllablla.
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend your Pocket workflow beyond your browser with Pocket Desktop. Get a different offline experience that’s completely safe and user-friendly..
        /// </summary>
        public static string descriptionDesktop {
            get {
                return ResourceManager.GetString("descriptionDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket now available on Google Play. Manage your expenses from wherever you are by downloading Pocket on your android device now!.
        /// </summary>
        public static string descriptionMobile {
            get {
                return ResourceManager.GetString("descriptionMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket is an application blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla blla.
        /// </summary>
        public static string descriptionPocket {
            get {
                return ResourceManager.GetString("descriptionPocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        public static string emergency {
            get {
                return ResourceManager.GetString("emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string extra {
            get {
                return ResourceManager.GetString("extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us:.
        /// </summary>
        public static string followus {
            get {
                return ResourceManager.GetString("followus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string forgotpassword {
            get {
                return ResourceManager.GetString("forgotpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string fullname {
            get {
                return ResourceManager.GetString("fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        public static string holidays {
            get {
                return ResourceManager.GetString("holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home care.
        /// </summary>
        public static string homecare {
            get {
                return ResourceManager.GetString("homecare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shqip.
        /// </summary>
        public static string languagesswitch {
            get {
                return ResourceManager.GetString("languagesswitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans.
        /// </summary>
        public static string loans {
            get {
                return ResourceManager.GetString("loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Login.
        /// </summary>
        public static string longsignin {
            get {
                return ResourceManager.GetString("longsignin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Sign up..
        /// </summary>
        public static string longsignup {
            get {
                return ResourceManager.GetString("longsignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical.
        /// </summary>
        public static string medical {
            get {
                return ResourceManager.GetString("medical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the new type:.
        /// </summary>
        public static string newtypename {
            get {
                return ResourceManager.GetString("newtypename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes:.
        /// </summary>
        public static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method:.
        /// </summary>
        public static string paymentmethod {
            get {
                return ResourceManager.GetString("paymentmethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string repeatpassword {
            get {
                return ResourceManager.GetString("repeatpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings.
        /// </summary>
        public static string savings {
            get {
                return ResourceManager.GetString("savings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string signup {
            get {
                return ResourceManager.GetString("signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Income:.
        /// </summary>
        public static string totalincome {
            get {
                return ResourceManager.GetString("totalincome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loans: .
        /// </summary>
        public static string totalloans {
            get {
                return ResourceManager.GetString("totalloans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction date:.
        /// </summary>
        public static string transactiondate {
            get {
                return ResourceManager.GetString("transactiondate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the type.
        /// </summary>
        public static string typename {
            get {
                return ResourceManager.GetString("typename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string utilities {
            get {
                return ResourceManager.GetString("utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wardrobe.
        /// </summary>
        public static string wardrobe {
            get {
                return ResourceManager.GetString("wardrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, .
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
    }
}
