//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pocket_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int IDIncome { get; set; }
        public int IDUser { get; set; }
        public string PersonName { get; set; }
        public double TotalIncome { get; set; }
        public System.DateTime SalaryDate { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<int> UpdateCounter { get; set; }
    
        public virtual User User { get; set; }
    }
}
